import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
const inter = Inter({ subsets: ['latin'] })
import { StoreProvider } from '@/utils/GlobalState';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
    <html lang="en">
      <body className={inter.className}>
      <Header/>
      <main className="flex min-h-screen flex-col items-center justify-between pb-[11rem]">
        {children}
      </main>  
      <Footer/>
      </body>
    </html>
    </StoreProvider>
  )
}
