export const ADD_ADMIN_DATA = 'ADD_ADMIN_DATA';
export const ADD_QUIZZER_DATA = 'ADD_QUIZZER_DATA';
export const ADD_QUIZRECS_DATA = 'ADD_QUIZRECS_DATA';
//export const ADD_IDEALOUTCOME_DATA = 'ADD_IDEALOUTCOME_DATA';